/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dialog;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import static java.lang.Thread.sleep;
/**
 *
 * @author AKSHAY
 */import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class Home extends javax.swing.JFrame implements Runnable{
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
 Thread t;
String msg="                                                     Welcome to Library Management System ";
boolean stopflag;
    /**
     * Creates new form Home
     */
    public Home() {
        super("Libary Management System");
        initComponents();
        setResizable(false);
        con=JavaConnect.connectDb();
        currentDate();
       
        jButton1.requestFocusInWindow();
        jButton1.setText("Show Tools");
         jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton7.setVisible(false);
        jLabel10.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel8.setVisible(false);
        jLabel7.setVisible(false);
        t=new Thread((Runnable)this);
        stopflag=false;
 t.start();
    }
 public void currentDate(){
        Thread clock=new Thread(){
            public void run(){
                for(;;){
                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    jLabel3.setText("Date :- "+day+"-"+(month+1)+"-"+year);
                    int hour=cal.get(Calendar.HOUR);
                    int minute=cal.get(Calendar.MINUTE);
                    int second=cal.get(Calendar.SECOND);
                    jLabel4.setText("Time :- "+hour+":"+minute+":"+second);
                    
                    try{
                        sleep(1000);
                    }catch(InterruptedException ex){
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE,null,ex);
                    }
                }
            }
        };
        clock.start();
    }
public void stop()
{
stopflag=true;
t=null;
}
 public void run()
{
try
{
while(true)
{
jLabel2.setText(msg);
char ch=msg.charAt(0);
msg=msg.substring(1);
msg=msg+ch;
if(stopflag)
break;
Thread.sleep(300);
}
}
catch(Exception e)
{
System.out.println("Interrupted Exception");
}
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Library Management System");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 0, 1344, 60);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 420, 161, 137);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(880, 420, 161, 137);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(590, 420, 161, 137);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stud.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(60, 420, 161, 137);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Book");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 560, 60, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Issue Book");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(600, 560, 132, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Member");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 560, 131, 23);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Return Book");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(890, 560, 148, 29);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Show Tools");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 90, 130, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 190, 580, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(750, 190, 580, 40);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1290, 90, 40, 40);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book-icon.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1160, 420, 160, 137);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Renew Book");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1170, 550, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 710);

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        jMenu1.setText("<html><h3>File</h3>");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem1.setText("Member");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem2.setText("Book");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem3.setText("Issue Book");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem4.setText("Return Book");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem11.setText("Renew Book");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);
        jMenu1.add(jSeparator1);

        jMenuItem5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("<html><h3>Reports</h3>");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem7.setText("Member Report");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem8.setText("Book Report");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem9.setText("Currently Issued Report");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jMenuItem10.setText("Complete Issued Report");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("<html><h3>About Us</h2>");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("<html><h3>Help</h3>");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1386, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Book ob=new Book();
         ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         IssueBook ob=new IssueBook();
         ob.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         ReturnBook ob=new ReturnBook();
         ob.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Member ob=new Member();
        
        ob.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

   
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("Show Tools".equals(jButton1.getText())){
            jButton1.setText("Hide Tools");
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(true);
            jButton7.setVisible(true);
            jLabel10.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel8.setVisible(true);
            jLabel7.setVisible(true);
        }
        else{
            jButton1.setText("Show Tools");
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jButton7.setVisible(false);
            jLabel10.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel8.setVisible(false);
            jLabel7.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Member ob=new Member();
         ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         Book ob=new Book();
         ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         IssueBook ob=new IssueBook();
         ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       ReturnBook ob=new ReturnBook();
         ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // Report All Members
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("Member_Report.pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult == JFileChooser.APPROVE_OPTION) {
            
            String filePath = dialog.getSelectedFile().getPath();
            
         try{
        String q="select memberid,firstname,lastname,age,gender,address,dob,email,mobile from Member";
        pst=con.prepareStatement(q);
        rs=pst.executeQuery();
         Document document=new Document();
            PdfWriter.getInstance(document,new FileOutputStream(filePath));
            document.open();
            document.add(new Paragraph("            Member Report",FontFactory.getFont(FontFactory.TIMES_BOLD,36,Font.BOLD)));
            //document.add(new Paragraph(new Date(WIDTH).toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
           document.add(new Paragraph("  "));
            PdfPTable table=new PdfPTable(7);
            PdfPCell cell=new PdfPCell(new Paragraph("Member Id"));
            cell.setColspan(1);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell);
            PdfPCell cell1=new PdfPCell(new Paragraph("Name"));
            cell1.setColspan(1);
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell1.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell1);
            PdfPCell cell3=new PdfPCell(new Paragraph("Gender"));
            cell3.setColspan(1);
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell3);
            PdfPCell cell4=new PdfPCell(new Paragraph("Address"));
            cell4.setColspan(1);
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell4.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell4);
            PdfPCell cell5=new PdfPCell(new Paragraph("DOB"));
            cell5.setColspan(1);
            cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell5.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell5);
            PdfPCell cell6=new PdfPCell(new Paragraph("Email Id"));
            cell6.setColspan(1);
            cell6.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell6.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell6);
            PdfPCell cell7=new PdfPCell(new Paragraph("Mobile No"));
            cell7.setColspan(1);
            cell7.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell7.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell7);
        while(rs.next()){
            String a=rs.getString(1);
            String b=rs.getString(2);
            String c=rs.getString(3);
            String bc=b+" "+c;
           
            String e=rs.getString(5);
            String f=rs.getString(6);
            String g=rs.getString(7);
            String h=rs.getString(8);
            String i=rs.getString(9);
           
            table.addCell(a);
            table.addCell(bc);
            
            table.addCell(e);
            table.addCell(f);
            table.addCell(g);
            table.addCell(h);
            table.addCell(i);
           
            
        }
         document.add(table);
            document.close();
        JOptionPane.showMessageDialog(null, "Report Generated...!!!");
        rs.close();
        pst.close();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }   catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
        try{
            rs.close();
            pst.close();
        }catch(SQLException e1){
            
        }
    }
        }  
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // Book Report
         JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("Book_Report.pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult == JFileChooser.APPROVE_OPTION) {
            
            String filePath = dialog.getSelectedFile().getPath();
            
         try{
        String q="select bookid,title,auther,edition,price,stock from Book";
        pst=con.prepareStatement(q);
        rs=pst.executeQuery();
         Document document=new Document();
            PdfWriter.getInstance(document,new FileOutputStream(filePath));
            document.open();
            document.add(new Paragraph("               Book Report",FontFactory.getFont(FontFactory.TIMES_BOLD,36,Font.BOLD)));
            //document.add(new Paragraph(new Date(WIDTH).toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
           document.add(new Paragraph("  "));
            PdfPTable table=new PdfPTable(6);
            PdfPCell cell=new PdfPCell(new Paragraph("Book Id"));
            cell.setColspan(1);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell);
            PdfPCell cell1=new PdfPCell(new Paragraph("Title"));
            cell1.setColspan(1);
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell1.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell1);
            PdfPCell cell3=new PdfPCell(new Paragraph("Auther"));
            cell3.setColspan(1);
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell3);
            PdfPCell cell4=new PdfPCell(new Paragraph("Edition"));
            cell4.setColspan(1);
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell4.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell4);
            PdfPCell cell5=new PdfPCell(new Paragraph("Price"));
            cell5.setColspan(1);
            cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell5.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell5);
             PdfPCell cell6=new PdfPCell(new Paragraph("Stock"));
            cell6.setColspan(1);
            cell6.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell6.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell6);
            
        while(rs.next()){
            String a=rs.getString(1);
            String b=rs.getString(2);
            String c=rs.getString(3);
            String e=rs.getString(4);
            String f=rs.getString(5);
            String g=rs.getString(6);
            table.addCell(a);
            table.addCell(b);
            table.addCell(c);
            table.addCell(e);
            table.addCell(f);
            table.addCell(g);
        }
         document.add(table);
            document.close();
        JOptionPane.showMessageDialog(null, "Report Generated...!!!");
        rs.close();
        pst.close();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }   catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
        try{
            rs.close();
            pst.close();
        }catch(SQLException e1){
            
        }
    }
        }  
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // Currently Issued Books Report
         JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("Currently_Issued_Report.pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult == JFileChooser.APPROVE_OPTION) {
            
            String filePath = dialog.getSelectedFile().getPath();
            
         try{
        String q="select * from Issue";
        pst=con.prepareStatement(q);
        rs=pst.executeQuery();
         Document document=new Document();
            PdfWriter.getInstance(document,new FileOutputStream(filePath));
            document.open();
            document.add(new Paragraph("       Currently Issued Report",FontFactory.getFont(FontFactory.TIMES_BOLD,36,Font.BOLD)));
            //document.add(new Paragraph(new Date(WIDTH).toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
           document.add(new Paragraph("  "));
            PdfPTable table=new PdfPTable(5);
            PdfPCell cell=new PdfPCell(new Paragraph("Member Id"));
            cell.setColspan(1);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell);
            PdfPCell cell1=new PdfPCell(new Paragraph("Name"));
            cell1.setColspan(1);
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell1.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell1);
            PdfPCell cell3=new PdfPCell(new Paragraph("Book Id"));
            cell3.setColspan(1);
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell3);
            PdfPCell cell4=new PdfPCell(new Paragraph("Title"));
            cell4.setColspan(1);
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell4.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell4);
            PdfPCell cell5=new PdfPCell(new Paragraph("Issue Date"));
            cell5.setColspan(1);
            cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell5.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell5);
            
        while(rs.next()){
            String a=rs.getString(1);
            String b=rs.getString(2);
            String c=rs.getString(3);
            String e=rs.getString(4);
            String f=rs.getString(5);
            
            table.addCell(a);
            table.addCell(b);
            table.addCell(c);
            table.addCell(e);
            table.addCell(f);
            
        }
         document.add(table);
            document.close();
        JOptionPane.showMessageDialog(null, "Report Created...!!!");
        rs.close();
        pst.close();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }   catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
        try{
            rs.close();
            pst.close();
        }catch(SQLException e1){
            
        }
    }
        }  
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // Total Issued Book Report
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("Complete_Issued_Report.pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult == JFileChooser.APPROVE_OPTION) {
            
            String filePath = dialog.getSelectedFile().getPath();
            
         try{
        String q="select * from IssueBook";
        pst=con.prepareStatement(q);
        rs=pst.executeQuery();
         Document document=new Document();
            PdfWriter.getInstance(document,new FileOutputStream(filePath));
            document.open();
            document.add(new Paragraph("       Complete Issued Report",FontFactory.getFont(FontFactory.TIMES_BOLD,36,Font.BOLD)));
            //document.add(new Paragraph(new Date(WIDTH).toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
           document.add(new Paragraph("  "));
            PdfPTable table=new PdfPTable(7);
            PdfPCell cell=new PdfPCell(new Paragraph("Member Id"));
            cell.setColspan(1);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell);
            PdfPCell cell2=new PdfPCell(new Paragraph("Name"));
            cell2.setColspan(1);
            cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell2.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell2);
            PdfPCell cell3=new PdfPCell(new Paragraph("Book Id"));
            cell3.setColspan(1);
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell3);
            PdfPCell cell4=new PdfPCell(new Paragraph("Title"));
            cell4.setColspan(1);
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell4.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell4);
            PdfPCell cell5=new PdfPCell(new Paragraph("Issue Date"));
            cell5.setColspan(1);
            cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell5.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell5);
            PdfPCell cell6=new PdfPCell(new Paragraph("Return Date"));
            cell6.setColspan(1);
            cell6.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell6.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell6);
            PdfPCell cell7=new PdfPCell(new Paragraph("Fine in Rupees"));
            cell7.setColspan(1);
            cell7.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell7.setBackgroundColor(BaseColor.CYAN);
            table.addCell(cell7);
            
        while(rs.next()){
          String a=rs.getString(1);
            String b=rs.getString(2);
            String c=rs.getString(3);
            String e=rs.getString(4);
            String f=rs.getString(5);
            String d=rs.getString(6);
            String g=rs.getString(7);         
            table.addCell(a);
            table.addCell(b);
            table.addCell(c);
            table.addCell(e);
            table.addCell(f);  
            table.addCell(d);
            table.addCell(g);
        }
         document.add(table);
            document.close();
        JOptionPane.showMessageDialog(null, "Report Generated...!!!");
        rs.close();
        pst.close();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }   catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
        try{
            rs.close();
            pst.close();
        }catch(SQLException e1){
            
        }
    }
        }  
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Renew ob=new Renew();
         ob.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Renew ob=new Renew();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
          try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"D:\\Database\\about_us.pdf");
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
          try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"D:\\Database\\help.pdf");
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
