
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.*;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.awt.Font;
import java.io.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.Image;

import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AKSHAY
 */
public final class Member extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst,pst1;
    ResultSet rs,rs1;
    /**
     * Creates new form Member
     */
    public void Random(){
        Random rd=new Random();
        jTextField1.setText(""+rd.nextInt(9999+1));
    }
    public Member() {
        super("Member");
        initComponents();
        setResizable(false);
        con=JavaConnect.connectDb();
        update();
        Random();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
     // setUndecorated(true);
     //  getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("Back to Home");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 5, true), "Member Registration", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 36), new java.awt.Color(255, 0, 0))); // NOI18N

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        jComboBox1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Email Id");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");

        jTextField4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("DOB");

        jTextField6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jComboBox3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2010", "2012", "2013", "2014", "2015" }));

        jTextField3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Member Id");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Age");

        jTextField2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton1.setText("Male");

        jTextField5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Address");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("First Name");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Mobile");

        jTextField7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton2.setText("Female");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setText("Attach Photo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap())
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(30, 30, 30)
                                                .addComponent(jRadioButton2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(149, 149, 149))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("Total Registered Members are");

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 5, true), "Smart Search Box", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Search by MemberId / First Name / Last Name / Mobile Number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setText("Create Membership Card / Library Card");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        setSize(new java.awt.Dimension(1270, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        setVisible(false);
        
    }//GEN-LAST:event_jLabel7MouseClicked
 public void clearData(){
         
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField9.setText("");
        buttonGroup1.clearSelection();
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        img.setIcon(null);
         Random();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Add Button
        try{
            String s1="select * from Member where memberid='"+jTextField1.getText()+"'";
            pst1=con.prepareStatement(s1);
              rs1=pst1.executeQuery();
             if(rs1.next())
                 JOptionPane.showMessageDialog(null, "Member Already Registered...!!!");
             else
             {
              String c1=jComboBox1.getSelectedItem().toString();
         String c2=jComboBox2.getSelectedItem().toString();
         String c3=jComboBox3.getSelectedItem().toString();
         String db=c1+"-"+c2+"-"+c3;
         String a=jTextField1.getText();
         String b=jTextField2.getText();
         String c=jTextField3.getText();
         String d=jTextField4.getText();
         String e=jTextField5.getText();
         String f=jTextField6.getText();
         String g=jTextField7.getText();
         if(b.length()!=0 && c.length()!=0 && d.length()!=0 && e.length()!=0 && f.length()!=0 && g.length()!=0){
          if(jRadioButton1.isSelected()==true || jRadioButton2.isSelected()==true){ 
          if(c2!="Month" && c1!="Day" && c3!="Year")
           {
          
           if(img.getIcon()!=null){
                 int p=JOptionPane.showConfirmDialog(null, "Are You Sure ?","Add Member",JOptionPane.YES_NO_OPTION);
               if(p==0){
            String s="insert into Member(memberid,firstname,lastname,age,gender,address,dob,email,mobile,image) values (?,?,?,?,?,?,?,?,?,?)";
            pst=con.prepareStatement(s);
            pst.setString(1, a);
            pst.setString(2, b);
            pst.setString(3, c);
            pst.setString(4, d);
             jRadioButton1.setActionCommand("Male");
            jRadioButton2.setActionCommand("Female");
            pst.setString(5, buttonGroup1.getSelection().getActionCommand());
            pst.setString(6, e);
            pst.setString(7,db);
            pst.setString(8, f);
            pst.setString(9, g);
            pst.setBytes(10, person_image);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Member Registered Successfully...!!!");
            clearData();
           
           }}
           else{
               JOptionPane.showMessageDialog(null, "Please Attach Photo...!!!");
           }
            }else{
                JOptionPane.showMessageDialog(null, "Please Select Date of Birth Properly...!!!");
            }
          }else{
              JOptionPane.showMessageDialog(null, "Please Select Gender...!!!");
          }
         }else{
             JOptionPane.showMessageDialog(null, "Please Insert All Data...!!!");
         }
         
             }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs1.close();
                pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
clearData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
            String s="select * from Member where memberid='"+jTextField1.getText()+"'";
              pst1=con.prepareStatement(s);
              rs=pst1.executeQuery();
              if(rs.next()){
             int p=JOptionPane.showConfirmDialog(null, "Are You Sure ?","Update Member",JOptionPane.YES_NO_OPTION);
               if(p==0){
                   String a=jTextField1.getText();
                   String b=jTextField2.getText();
                   String c=jTextField3.getText();
                   String d=jTextField4.getText();
                   String e=jTextField5.getText();
                   String f=jTextField6.getText();
                   String g=jTextField7.getText();
                   String c1=jComboBox1.getSelectedItem().toString();
                   String c2=jComboBox2.getSelectedItem().toString();
                   String c3=jComboBox3.getSelectedItem().toString();
                   String db=c1+"-"+c2+"-"+c3;
                  String q="update Member set firstname=?,lastname=?,age=?,gender=?,address=?,dob=?,email=?,mobile=?,image=? where memberid=?";
                   pst=con.prepareStatement(q);
                   pst.setString(10, a);
                   pst.setString(1, b);
                   pst.setString(2, c);
                   pst.setString(3, d);
                    jRadioButton1.setActionCommand("Male");
                    jRadioButton2.setActionCommand("Female");
                   pst.setString(4, buttonGroup1.getSelection().getActionCommand());
                   pst.setString(5, e);
                   pst.setString(6,db);
                   pst.setString(7, f);
                   pst.setString(8, g);
                   pst.setBytes(9, person_image);
                   pst.execute();
                    JOptionPane.showMessageDialog(null, "Member Updated Successfully...!!!");
                    
              }
              }else
                  JOptionPane.showMessageDialog(null, "Firstly select/search Member to Update...!!!");
              
       }catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
       finally{
            try{
                rs1.close();
                pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }update();
       clearData();
    }//GEN-LAST:event_jButton2ActionPerformed
   public void counter(){
       try{
            String s="select count(memberid) from Member";
            pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                String sum=rs.getString("count(memberid)");
                jTextField8.setText(sum);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
   }
    public void update(){
    try{
        String q="select memberid,firstname,lastname,age,gender,address,dob,email,mobile from Member";
        pst=con.prepareStatement(q);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }finally{
        try{
            rs.close();
            pst.close();
        }catch(SQLException e1){
            
        }
    }
    counter();
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
          try{
              String s="select * from Member where memberid='"+jTextField1.getText()+"'";
              pst1=con.prepareStatement(s);
              rs=pst1.executeQuery();
              if(rs.next()){
             int p=JOptionPane.showConfirmDialog(null, "Are You Sure ?","Delete Membar",JOptionPane.YES_NO_OPTION);
               if(p==0){
             String q="delete from Member where memberid=?";
             pst=con.prepareStatement(q);
              pst.setString(1, jTextField1.getText());
              pst.execute();
              JOptionPane.showMessageDialog(null, "Member Deleted Successfully...!!!");
               
              }
              }else
                  JOptionPane.showMessageDialog(null, "Firstly select/search Member to delete...!!!");
              
          }catch(HeadlessException | SQLException e){
              JOptionPane.showMessageDialog(null, e);
          }finally{
            try{
                rs.close();
                pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
      update();
      clearData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f=chooser.getSelectedFile();
       filename=f.getAbsolutePath();
       ImageIcon imageIcon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
       img.setIcon(imageIcon);
       try{
           File image=new File(filename);
           FileInputStream fin=new FileInputStream(image);
           ByteArrayOutputStream bos=new ByteArrayOutputStream();
           byte[] buf=new byte[2048];
           for(int num;(num=fin.read(buf))!=-1;){
               bos.write(buf,0,num);
           }
           person_image=bos.toByteArray();
           
       }catch(FileNotFoundException e){
           JOptionPane.showMessageDialog(null, e);
       } catch (IOException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        String tableclick=(jTable1.getModel().getValueAt(row, 0).toString());
        try{
            String q="select image from Member where memberid='"+tableclick+"'";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            if(rs.next()){
                byte[] imagedata=rs.getBytes("image");
              
                ImageIcon imageIcon=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
               img.setIcon(imageIcon);
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String s="select * from Member where memberid='"+tableclick+"'";
             pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                String a=rs.getString(1);
                jTextField1.setText(a);
                 String b=rs.getString(2);
                jTextField2.setText(b);
                String c=rs.getString(3);
                jTextField3.setText(c);
                String d=rs.getString(4);
                jTextField4.setText(d);
                String e=rs.getString(5).trim();
                if("Male".equals(e)){
                    jRadioButton1.setSelected(true);
                   jRadioButton2.setSelected(false);
                }else{
                    jRadioButton1.setSelected(false);
                   jRadioButton2.setSelected(true);
                }
                String f=rs.getString(6);
                jTextField5.setText(f);
                String aa=rs.getString(7);
               String ss1=aa.substring(0, 2);
               int g=Integer.parseInt(ss1);
              jComboBox1.setSelectedIndex(g);
                int len=aa.length();
                String ss2=aa.substring(3, len-5).trim();
                jComboBox2.setSelectedItem(ss2);
                String ss3=aa.substring(len-4, len).trim();
                jComboBox3.setSelectedItem(ss3);
                String h=rs.getString(8);
                jTextField6.setText(h);
                String i=rs.getString(9);
                jTextField7.setText(i);
            }
        }catch(SQLException e1){
            
        }finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        //Search Box
        
       try{
            String q="select image from Member where memberid='"+jTextField9.getText()+"'";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            if(rs.next()){
                byte[] imagedata=rs.getBytes("image");
              
                ImageIcon imageIcon=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
               img.setIcon(imageIcon);
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
       finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String s="select * from Member where memberid='"+jTextField9.getText()+"'";
             pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                String a=rs.getString(1);
                jTextField1.setText(a);
                 String b=rs.getString(2);
                jTextField2.setText(b);
                String c=rs.getString(3);
                jTextField3.setText(c);
                String d=rs.getString(4);
                jTextField4.setText(d);
                String e=rs.getString(5).trim();
                if("Male".equals(e)){
                    jRadioButton1.setSelected(true);
                   jRadioButton2.setSelected(false);
                }else{
                    jRadioButton1.setSelected(false);
                   jRadioButton2.setSelected(true);
                }
                String f=rs.getString(6);
                jTextField5.setText(f);
                String aa=rs.getString(7);
               String ss1=aa.substring(0, 2);
               int g=Integer.parseInt(ss1);
              jComboBox1.setSelectedIndex(g);
                int len=aa.length();
                String ss2=aa.substring(3, len-5).trim();
                jComboBox2.setSelectedItem(ss2);
                String ss3=aa.substring(len-4, len).trim();
                jComboBox3.setSelectedItem(ss3);
                String h=rs.getString(8);
                jTextField6.setText(h);
                String i=rs.getString(9);
                jTextField7.setText(i);
            }
        }catch(SQLException e1){
            
        }finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String q="select image from Member where firstname='"+jTextField9.getText()+"'";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            if(rs.next()){
                byte[] imagedata=rs.getBytes("image");
              
                ImageIcon imageIcon=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
               img.setIcon(imageIcon);
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }finally{
            try{
                rs.close();
             //   pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String s="select * from Member where firstname='"+jTextField9.getText()+"'";
             pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                String a=rs.getString(1);
                jTextField1.setText(a);
                 String b=rs.getString(2);
                jTextField2.setText(b);
                String c=rs.getString(3);
                jTextField3.setText(c);
                String d=rs.getString(4);
                jTextField4.setText(d);
                String e=rs.getString(5).trim();
                if("Male".equals(e)){
                    jRadioButton1.setSelected(true);
                   jRadioButton2.setSelected(false);
                }else{
                    jRadioButton1.setSelected(false);
                   jRadioButton2.setSelected(true);
                }
                String f=rs.getString(6);
                jTextField5.setText(f);
                String aa=rs.getString(7);
               String ss1=aa.substring(0, 2);
               int g=Integer.parseInt(ss1);
              jComboBox1.setSelectedIndex(g);
                int len=aa.length();
                String ss2=aa.substring(3, len-5).trim();
                jComboBox2.setSelectedItem(ss2);
                String ss3=aa.substring(len-4, len).trim();
                jComboBox3.setSelectedItem(ss3);
                String h=rs.getString(8);
                jTextField6.setText(h);
                String i=rs.getString(9);
                jTextField7.setText(i);
            }
        }catch(SQLException e1){
            
        }finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String q="select image from Member where lastname='"+jTextField9.getText()+"'";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            if(rs.next()){
                byte[] imagedata=rs.getBytes("image");
              
                ImageIcon imageIcon=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
               img.setIcon(imageIcon);
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String s="select * from Member where lastname='"+jTextField9.getText()+"'";
             pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                String a=rs.getString(1);
                jTextField1.setText(a);
                 String b=rs.getString(2);
                jTextField2.setText(b);
                String c=rs.getString(3);
                jTextField3.setText(c);
                String d=rs.getString(4);
                jTextField4.setText(d);
                String e=rs.getString(5).trim();
                if("Male".equals(e)){
                    jRadioButton1.setSelected(true);
                   jRadioButton2.setSelected(false);
                }else{
                    jRadioButton1.setSelected(false);
                   jRadioButton2.setSelected(true);
                }
                String f=rs.getString(6);
                jTextField5.setText(f);
                String aa=rs.getString(7);
               String ss1=aa.substring(0, 2);
               int g=Integer.parseInt(ss1);
              jComboBox1.setSelectedIndex(g);
                int len=aa.length();
                String ss2=aa.substring(3, len-5).trim();
                jComboBox2.setSelectedItem(ss2);
                String ss3=aa.substring(len-4, len).trim();
                jComboBox3.setSelectedItem(ss3);
                String h=rs.getString(8);
                jTextField6.setText(h);
                String i=rs.getString(9);
                jTextField7.setText(i);
            }
        }catch(SQLException e1){
            
        }finally{
            try{
                rs.close();
                //pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String q="select image from Member where mobile='"+jTextField9.getText()+"'";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            if(rs.next()){
                byte[] imagedata=rs.getBytes("image");
              
                ImageIcon imageIcon=new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
               img.setIcon(imageIcon);
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }finally{
            try{
                rs.close();
              //  pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
        try{
            String s="select * from Member where mobile='"+jTextField9.getText()+"'";
             pst=con.prepareStatement(s);
            rs=pst.executeQuery();
            if(rs.next()){
                String a=rs.getString(1);
                jTextField1.setText(a);
                 String b=rs.getString(2);
                jTextField2.setText(b);
                String c=rs.getString(3);
                jTextField3.setText(c);
                String d=rs.getString(4);
                jTextField4.setText(d);
                String e=rs.getString(5).trim();
                if("Male".equals(e)){
                    jRadioButton1.setSelected(true);
                   jRadioButton2.setSelected(false);
                }else{
                    jRadioButton1.setSelected(false);
                   jRadioButton2.setSelected(true);
                }
                String f=rs.getString(6);
                jTextField5.setText(f);
                String aa=rs.getString(7);
               String ss1=aa.substring(0, 2);
               int g=Integer.parseInt(ss1);
              jComboBox1.setSelectedIndex(g);
                int len=aa.length();
                String ss2=aa.substring(3, len-5).trim();
                jComboBox2.setSelectedItem(ss2);
                String ss3=aa.substring(len-4, len).trim();
                jComboBox3.setSelectedItem(ss3);
                String h=rs.getString(8);
                jTextField6.setText(h);
                String i=rs.getString(9);
                jTextField7.setText(i);
            }
        }catch(SQLException e1){
            
        }finally{
            try{
                rs.close();
               // pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Create MemberShip Card
        try{
             String a=jTextField1.getText();
       String aa="select * from Member where memberid='"+a+"'";
       pst=con.prepareStatement(aa);
       rs=pst.executeQuery();
      if(rs.next()){
         JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File(rs.getString(2)+"_"+rs.getString(3)+".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult == JFileChooser.APPROVE_OPTION) {
            
            String filePath = dialog.getSelectedFile().getPath();
            
         
         Document document=new Document();
            PdfWriter.getInstance(document,new FileOutputStream(filePath));
            document.open();
            document.add(new Paragraph("     Membership / Library Card ",FontFactory.getFont(FontFactory.TIMES_BOLD,36,Font.BOLD)));
            //document.add(new Paragraph(new Date(WIDTH).toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
           // document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
           document.add(new Paragraph("  "));
            PdfPTable table=new PdfPTable(2);
            PdfPCell cell=new PdfPCell(new Paragraph("Member Id"));
            table.addCell(cell);
            PdfPCell cell2=new PdfPCell(new Paragraph(rs.getString(1)));
           table.addCell(cell2);
            PdfPCell cell3=new PdfPCell(new Paragraph("Name"));
            table.addCell(cell3);
            PdfPCell cell4=new PdfPCell(new Paragraph(rs.getString(2)+" "+rs.getString(3)));
            table.addCell(cell4);
            PdfPCell cell5=new PdfPCell(new Paragraph("DOB"));
            table.addCell(cell5);
            PdfPCell cell6=new PdfPCell(new Paragraph(rs.getString(7)));
             table.addCell(cell6);
           PdfPCell cell7=new PdfPCell(new Paragraph("Address"));
             table.addCell(cell7);
              PdfPCell cell8=new PdfPCell(new Paragraph(rs.getString(6)));
             table.addCell(cell8);
              PdfPCell cell9=new PdfPCell(new Paragraph("Email Id"));
             table.addCell(cell9);
              PdfPCell cell10=new PdfPCell(new Paragraph(rs.getString(8)));
             table.addCell(cell10);
              PdfPCell cell11=new PdfPCell(new Paragraph("Mobile No"));
             table.addCell(cell11); 
             PdfPCell cell12=new PdfPCell(new Paragraph(rs.getString(9)));
             table.addCell(cell12);
             
         document.add(table);
            document.close();
        JOptionPane.showMessageDialog(null, "Membership Card Generated...!!!");
        } 
      }else
          JOptionPane.showMessageDialog(null, "Firslty Select/Search Registered Member...!!!");
     
        } 
       catch (FileNotFoundException | DocumentException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }finally{
            try{
                rs.close();
              //  pst1.close();
                pst.close();
                        
            }catch(SQLException e1){
                
            }
        }
         
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
private ImageIcon format=null;
String filename=null;
byte[] person_image=null;

    private String String(int length) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
